#!/bin/bash
#
# Take a pathname as an argument and output a playlist to standard
# output and errors to standard error.
#
# The output format is repeated sequences of:
#
#   <pathname>\t<artist>\t<title>\t<key>[\t<bpm>]\n

set -eu -o pipefail  # pipefail requires bash, not sh

PATHNAME="$1"

if [ -d "$PATHNAME" ] && [ -x "$(command -v mediainfo)" ]; then
    find -L "$PATHNAME" -type f -regextype posix-egrep \
        -iregex '.*\.(ogg|oga|aac|cdaudio|mp3|flac|wav|aif|aiff|m4a|wma)' |
        while read file; do
            mi=$(mediainfo --Inform="General;%Performer%\t%Track%\t%Initial key%\t%BPM%\n" "$file")
            [ "$mi" != "" ] && echo -e "`realpath "$file"`\t$mi"
        done
    elif [ -f "$PATHNAME" ]; then
        cat "$PATHNAME"
    else
        echo -e "This script requires 'mediainfo'\nInstall with 'pacman -S mediainfo'"
        exit 1
fi
